spring.application.name=fincore
spring.datasource.url=jdbc:postgresql://localhost:5432/fincore
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
