CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) UNIQUE NOT NULL,
    password_hash varchar(255) NOT NULL,
    role varchar(20) NOT NULL CHECK(role IN('ADMIN', 'USER')),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);