CREATE TABLE accounts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id       BIGINT             NOT NULL,
    account_number VARCHAR(25) UNIQUE NOT NULL,
    currency       VARCHAR(3)         NOT NULL CHECK (currency IN ('MXN')),
    balance        NUMERIC(19, 2)     NOT NULL DEFAULT 0.00 CHECK (balance >= 0),
    status         VARCHAR(20)        NOT NULL CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED')),
    version        INTEGER            NOT NULL DEFAULT 0,
    created_at     TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_accounts_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);