CREATE TABLE transfers
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_account_id      BIGINT         NOT NULL,
    destination_account_id BIGINT         NOT NULL,
    amount                 NUMERIC(19, 2) NOT NULL CHECK (amount > 0),
    status                 VARCHAR(20)    NOT NULL CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    created_at             TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at           TIMESTAMP      NULL,

    CONSTRAINT fk_transfers_source_account_id FOREIGN KEY (source_account_id) REFERENCES accounts (id),
    CONSTRAINT fk_transfers_destination_account_id FOREIGN KEY (destination_account_id) REFERENCES accounts (id),

    CONSTRAINT chk_transfers_different_accounts CHECK (source_account_id <> destination_account_id)
);
