CREATE TABLE ledger_entries
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id   BIGINT         NOT NULL,
    account_id    BIGINT         NOT NULL,
    entry_type    VARCHAR(20)    NOT NULL CHECK (entry_type IN ('DEBIT', 'CREDIT')),
    amount        NUMERIC(19, 2) NOT NULL CHECK (amount > 0),
    balance_after NUMERIC(19, 2) NOT NULL,
    created_at    TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ledger_entries_transfer_id FOREIGN KEY (transfer_id) REFERENCES transfers (id),
    CONSTRAINT fk_ledger_entries_account_id FOREIGN KEY (account_id) REFERENCES accounts (id)
);
